import type { Metadata } from "next"
import { notFound, redirect } from "next/navigation"
import { setRequestLocale } from "next-intl/server"
import { getTranslations } from "next-intl/server"
import { Link } from "@/i18n/navigation"
import { CALCULATORS, getCalculatorBySlug } from "@/lib/data/calculators"
import { CATEGORIES } from "@/lib/data/categories"
import { CALCULATOR_COMPONENTS } from "@/lib/data/calculator-components"
import { getCalculatorArticle } from "@/lib/data/calculator-articles"
import { getCalculatorHowTo } from "@/lib/data/calculator-howto"
import { getSlugByLocale, getEnglishSlug, getAllLocalizedSlugs } from "@/lib/data/calculator-slugs"
import { CROSS_LINKS } from "@/lib/data/calculator-crosslinks"
import { getTablesForCategory } from "@/lib/data/calculator-tables"
import { getAuthorBySlug, PRIMARY_AUTHOR_SLUG } from "@/lib/data/authors"
import { getCaseStudies } from "@/lib/data/calculator-case-studies"
import { getUzExtraFaq } from "@/lib/data/calculator-faq-uz-extras"
import type { CategoryId } from "@/lib/types/calculator"
import { ChevronRight, Home, ArrowRight, Calendar, ExternalLink, ShieldCheck, FlaskConical } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { DynamicIcon } from "@/components/calculator/DynamicIcon"
import { ErrorBoundary } from "@/components/calculator/ErrorBoundary"
import { SharePrintButtons } from "@/components/calculator/SharePrintButtons"
import { LinkifiedParagraph } from "@/components/calculator/LinkifiedParagraph"
import {
  Accordion,
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
} from "@/components/ui/accordion"

const BASE_URL = "https://calk.uz"

function CalculatorRenderer({ slug }: { slug: string }) {
  const Component = CALCULATOR_COMPONENTS[slug]

  if (!Component) {
    return (
      <div className="text-center py-12 text-muted-foreground">
        <DynamicIcon name="Calculator" className="h-12 w-12 mx-auto mb-4 opacity-50" />
        <p>Calculator component not found for: {slug}</p>
      </div>
    )
  }

  return <Component />
}

export function generateStaticParams() {
  return getAllLocalizedSlugs()
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string; slug: string }>
}): Promise<Metadata> {
  const { locale, slug } = await params

  // Resolve localized slug to english, then look up calculator
  const englishSlug = getEnglishSlug(slug, locale) ?? slug
  const calc = getCalculatorBySlug(englishSlug)

  if (!calc) {
    return { title: "404" }
  }

  const article = getCalculatorArticle(englishSlug)
  const title = locale === "uz" ? calc.titleUz : calc.titleRu
  const description = locale === "uz" ? calc.descriptionUz : calc.descriptionRu
  const lastUpdated = article?.lastUpdated || "2026-01-01"

  // Canonical URL always uses the localized slug
  const localizedSlugRu = getSlugByLocale(calc.slug, 'ru')
  const localizedSlugUz = getSlugByLocale(calc.slug, 'uz')
  const canonicalUrl = `${BASE_URL}/${locale}/calculator/${getSlugByLocale(calc.slug, locale)}`

  return {
    title,
    description,
    keywords: calc.keywords,
    alternates: {
      canonical: canonicalUrl,
      languages: {
        ru: `${BASE_URL}/ru/calculator/${localizedSlugRu}`,
        uz: `${BASE_URL}/uz/calculator/${localizedSlugUz}`,
        "x-default": `${BASE_URL}/ru/calculator/${localizedSlugRu}`,
      },
    },
    openGraph: {
      title: `${title} | Calk.UZ`,
      description,
      type: "website",
      locale: locale === "uz" ? "uz_UZ" : "ru_RU",
      alternateLocale: locale === "uz" ? "ru_RU" : "uz_UZ",
      url: canonicalUrl,
      siteName: "Calk.UZ",
      // og:image is auto-generated by opengraph-image.tsx
    },
    twitter: {
      card: "summary_large_image",
      title: `${title} | Calk.UZ`,
      description,
    },
    other: {
      "article:published_time": "2025-01-01T00:00:00+05:00",
      "article:modified_time": `${lastUpdated}T00:00:00+05:00`,
    },
  }
}

export default async function CalculatorPage({
  params,
}: {
  params: Promise<{ locale: string; slug: string }>
}) {
  const { locale, slug } = await params
  setRequestLocale(locale)
  const t = await getTranslations()

  // Resolve slug: could be English, Russian, or Uzbek
  const englishSlug = getEnglishSlug(slug, locale) ?? slug
  const calc = getCalculatorBySlug(englishSlug)
  if (!calc) {
    notFound()
  }

  // If the user hit an English slug (not the localized one), redirect to the localized URL
  const localizedSlug = getSlugByLocale(calc.slug, locale)
  if (slug !== localizedSlug && slug === calc.slug) {
    redirect(`/${locale}/calculator/${localizedSlug}`)
  }

  const category = CATEGORIES[calc.category]
  const categoryName = locale === "uz" ? category.nameUz : category.nameRu
  const title = locale === "uz" ? calc.titleUz : calc.titleRu
  const description = locale === "uz" ? calc.descriptionUz : calc.descriptionRu

  // Get related calculators (same category, excluding current)
  const relatedCalculators = CALCULATORS.filter(
    (c) => c.category === calc.category && c.slug !== calc.slug
  )
    .sort((a, b) => a.priority - b.priority)
    .slice(0, 4)

  // Get cross-category links
  const crossLinkSlugs = CROSS_LINKS[calc.slug] ?? []
  const crossLinkedCalculators = crossLinkSlugs
    .map((slug) => CALCULATORS.find((c) => c.slug === slug))
    .filter((c): c is NonNullable<typeof c> => c != null)

  // Get article data
  const article = getCalculatorArticle(calc.slug)
  const articleParagraphs = article
    ? locale === "uz"
      ? article.paragraphsUz
      : article.paragraphsRu
    : null
  // Augment Uzbek FAQ with locale-specific items (mahalla, OTM, BHK, etc.)
  // so the UZ pages have unique content beyond a translation of the RU version.
  const baseFaq = article
    ? (locale === "uz" ? article.faqUz : article.faqRu)
    : null
  const uzExtras = locale === "uz" ? getUzExtraFaq(calc.slug) : []
  const faqItems = baseFaq ? [...baseFaq, ...uzExtras] : null

  // Get HowTo data
  const howTo = getCalculatorHowTo(calc.slug)
  const howToSteps = howTo
    ? locale === "uz" ? howTo.stepsUz : howTo.stepsRu
    : null

  // Real-world case studies (priority-1 calculators)
  const caseStudies = getCaseStudies(calc.slug)

  // Schema.org JSON-LD — always use localized canonical URL
  const canonicalUrl = `${BASE_URL}/${locale}/calculator/${localizedSlug}`

  const webApplicationSchema = {
    "@context": "https://schema.org",
    "@type": "WebApplication",
    name: title,
    description,
    url: canonicalUrl,
    applicationCategory: "FinanceApplication",
    operatingSystem: "All",
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "UZS",
    },
    inLanguage: locale === "uz" ? "uz" : "ru",
    publisher: {
      "@type": "Organization",
      name: "Calk.UZ",
      url: BASE_URL,
    },
  }

  const breadcrumbSchema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: t("breadcrumb_home"),
        item: `${BASE_URL}/${locale}`,
      },
      {
        "@type": "ListItem",
        position: 2,
        name: categoryName,
        item: `${BASE_URL}/${locale}/category/${calc.category}`,
      },
      {
        "@type": "ListItem",
        position: 3,
        name: title,
        item: canonicalUrl,
      },
    ],
  }

  const faqSchema =
    faqItems && faqItems.length > 0
      ? {
          "@context": "https://schema.org",
          "@type": "FAQPage",
          mainEntity: faqItems.map((item) => ({
            "@type": "Question",
            name: item.question,
            acceptedAnswer: {
              "@type": "Answer",
              text: item.answer,
            },
          })),
        }
      : null

  const articleLastUpdated = article?.lastUpdated || "2026-01-01"

  const author = getAuthorBySlug(PRIMARY_AUTHOR_SLUG)
  const articleDatePublished = article?.datePublished || "2025-09-01"

  const techArticleSchema = articleParagraphs
    ? {
        "@context": "https://schema.org",
        "@type": "TechArticle",
        headline: title,
        description,
        url: canonicalUrl,
        datePublished: articleDatePublished,
        dateModified: articleLastUpdated,
        author: author
          ? {
              "@type": "Person",
              "@id": `${BASE_URL}/#founder`,
              name: author.name,
              alternateName: author.alternateName,
              url: `${BASE_URL}/${locale}/author/${author.slug}`,
              jobTitle: locale === "uz" ? author.jobTitleUz : author.jobTitleRu,
              image: `${BASE_URL}${author.imagePath}`,
            }
          : { "@type": "Organization", name: "Calk.UZ", url: BASE_URL },
        reviewedBy: {
          "@type": "Organization",
          name: "Calk.UZ",
          url: BASE_URL,
        },
        publisher: {
          "@type": "Organization",
          "@id": `${BASE_URL}/#organization`,
          name: "Calk.UZ",
          url: BASE_URL,
          logo: {
            "@type": "ImageObject",
            url: `${BASE_URL}/favicon.svg`,
          },
        },
        inLanguage: locale === "uz" ? "uz" : "ru",
        mainEntityOfPage: canonicalUrl,
      }
    : null

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const jsonLdArray: Record<string, any>[] = [webApplicationSchema, breadcrumbSchema]
  if (faqSchema) {
    jsonLdArray.push(faqSchema)
  }
  if (techArticleSchema) {
    jsonLdArray.push(techArticleSchema)
  }



  return (
    <div className="min-h-screen">
      {/* Schema.org JSON-LD */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(jsonLdArray),
        }}
      />

      {/* Breadcrumbs */}
      <div className="border-b border-border bg-muted/30">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-3">
          <nav className="flex items-center gap-1.5 text-sm text-muted-foreground">
            <Link
              href="/"
              className="flex items-center gap-1 hover:text-foreground transition-colors"
            >
              <Home className="h-3.5 w-3.5" />
              {t("breadcrumb_home")}
            </Link>
            <ChevronRight className="h-3.5 w-3.5" />
            <Link
              href={`/category/${calc.category}`}
              className="hover:text-foreground transition-colors"
            >
              {categoryName}
            </Link>
            <ChevronRight className="h-3.5 w-3.5" />
            <span className="text-foreground font-medium truncate max-w-[200px]">
              {title}
            </span>
          </nav>
        </div>
      </div>

      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Main Content */}
          <div className="lg:col-span-2">
            {/* Calculator Header */}
            <div className="mb-8">
              <div className="flex items-center gap-3 mb-4">
                <div
                  className={`flex h-12 w-12 items-center justify-center rounded-xl ${category.color}`}
                >
                  <DynamicIcon
                    name={calc.icon}
                    className={`h-6 w-6 ${category.iconColor}`}
                  />
                </div>
                <div>
                  <Badge variant="secondary" className="mb-1">
                    {categoryName}
                  </Badge>
                  <h1 className="text-2xl sm:text-3xl font-bold text-foreground">
                    {title}
                  </h1>
                </div>
              </div>
              <p className="text-muted-foreground leading-relaxed max-w-2xl">
                {description}
              </p>
              <div className="mt-3 flex flex-wrap items-center gap-4">
                <SharePrintButtons />
                {article?.lastUpdated && (
                  <span className="inline-flex items-center gap-1.5 text-xs text-muted-foreground">
                    <Calendar className="h-3.5 w-3.5" />
                    {t("last_updated")}: {article.lastUpdated}
                  </span>
                )}
              </div>
            </div>

            {/* Calculator Component */}
            <div className="rounded-2xl border border-border bg-card p-6 sm:p-8">
              <ErrorBoundary locale={locale}>
                <CalculatorRenderer slug={calc.slug} />
              </ErrorBoundary>
            </div>

            {/* Practical case studies — unique editorial content for priority-1 calcs */}
            {caseStudies && caseStudies.cases.length > 0 && (
              <div className="mt-8 rounded-2xl border border-border bg-card p-6 sm:p-8">
                <div className="flex items-center gap-2.5 mb-1">
                  <FlaskConical className="h-5 w-5 text-emerald-600 dark:text-emerald-400" />
                  <h2 className="text-lg sm:text-xl font-bold text-foreground">
                    {locale === "uz" ? "Amaliy misollar" : "Практические примеры"}
                  </h2>
                </div>
                <p className="text-sm text-muted-foreground mb-5">
                  {locale === "uz"
                    ? `${caseStudies.calibratedFor}-yil uchun yangilangan haqiqiy stsenariylar`
                    : `Реальные сценарии, актуализированные для ${caseStudies.calibratedFor} года`}
                </p>
                <div className="space-y-5">
                  {caseStudies.cases.map((cs, idx) => {
                    const steps = locale === "uz" ? cs.stepsUz : cs.stepsRu
                    return (
                      <div
                        key={idx}
                        className="rounded-xl border border-border bg-muted/20 p-4 sm:p-5"
                      >
                        <h3 className="text-base font-semibold text-foreground">
                          {locale === "uz" ? cs.titleUz : cs.titleRu}
                        </h3>
                        <p className="text-xs text-muted-foreground mt-0.5 mb-3">
                          {locale === "uz" ? cs.contextUz : cs.contextRu}
                        </p>
                        <dl className="grid grid-cols-1 sm:grid-cols-2 gap-x-4 gap-y-1.5">
                          {steps.map((step, sIdx) => (
                            <div
                              key={sIdx}
                              className="flex items-baseline justify-between gap-3 border-b border-border/50 pb-1"
                            >
                              <dt className="text-xs text-muted-foreground">{step.label}</dt>
                              <dd className="text-sm font-medium text-foreground tabular-nums">
                                {step.value}
                              </dd>
                            </div>
                          ))}
                        </dl>
                        <p className="text-sm text-muted-foreground mt-3 leading-relaxed border-l-2 border-emerald-500 pl-3">
                          {locale === "uz" ? cs.conclusionUz : cs.conclusionRu}
                        </p>
                      </div>
                    )
                  })}
                </div>
              </div>
            )}

            {/* HowTo Steps */}
            {howToSteps && howToSteps.length > 0 && (
              <div className="mt-8 rounded-2xl border border-border bg-card p-6 sm:p-8">
                <h2 className="text-lg sm:text-xl font-bold text-foreground mb-1">
                  {t("howto_heading")}
                </h2>
                <p className="text-sm text-muted-foreground mb-4">
                  {t("howto_time")}: ~{howTo!.totalTimeMinutes} {t("howto_minutes")}
                </p>
                <ol className="space-y-3">
                  {howToSteps.map((step, index) => (
                    <li key={index} className="flex gap-3">
                      <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary/10 text-primary text-sm font-semibold">
                        {index + 1}
                      </span>
                      <div className="pt-0.5">
                        <p className="font-medium text-foreground">{step.name}</p>
                        <p className="text-sm text-muted-foreground mt-0.5">{step.text}</p>
                      </div>
                    </li>
                  ))}
                </ol>
              </div>
            )}

            {/* Cross-category links */}
            {crossLinkedCalculators.length > 0 && (
              <div className="mt-6 p-4 rounded-xl bg-muted/30 border border-border">
                <h3 className="font-semibold text-foreground mb-3">
                  {t("see_also")}
                </h3>
                <div className="flex flex-wrap gap-2">
                  {crossLinkedCalculators.map((linked) => {
                    const linkedTitle = locale === "uz" ? linked.titleUz : linked.titleRu
                    const linkedSlug = getSlugByLocale(linked.slug, locale)
                    const linkedCategory = CATEGORIES[linked.category]
                    return (
                      <Link
                        key={linked.slug}
                        href={`/calculator/${linkedSlug}`}
                        className="inline-block"
                      >
                        <Badge
                          variant="secondary"
                          className="cursor-pointer hover:bg-accent transition-colors"
                        >
                          <DynamicIcon
                            name={linkedCategory.icon}
                            className={`h-3 w-3 mr-1.5 ${linkedCategory.iconColor}`}
                          />
                          {linkedTitle}
                        </Badge>
                      </Link>
                    )
                  })}
                </div>
              </div>
            )}

            {/* SEO Article Section */}
            {articleParagraphs && articleParagraphs.length > 0 && (
              <div className="mt-10">
                <h2 className="text-xl sm:text-2xl font-bold text-foreground mb-4">
                  {t("article_heading")}
                </h2>
                <div className="prose prose-sm sm:prose-base max-w-none text-muted-foreground space-y-4">
                  {articleParagraphs.map((paragraph, index) => {
                    const subheadingKeys = [
                      "article_h3_how_it_works",
                      "article_h3_formula",
                      "article_h3_example",
                      "article_h3_considerations",
                      "article_h3_tips",
                    ]
                    const subheadingKey = subheadingKeys[index]
                    return (
                      <div key={index}>
                        {subheadingKey && (
                          <h3 className="text-lg font-semibold text-foreground mt-6 mb-2">
                            {t(subheadingKey)}
                          </h3>
                        )}
                        <p className="leading-relaxed">
                          <LinkifiedParagraph
                            text={paragraph}
                            locale={locale}
                            currentSlug={calc.slug}
                          />
                        </p>
                      </div>
                    )
                  })}
                </div>

                {/* Data Tables */}
                {(() => {
                  const tables = getTablesForCategory(calc.category)
                  if (tables.length === 0) return null
                  return (
                    <div className="mt-8 space-y-6">
                      <h3 className="text-lg sm:text-xl font-semibold text-foreground">
                        {t("article_tables_heading")}
                      </h3>
                      {tables.map((table, tIdx) => (
                        <div key={tIdx} className="overflow-x-auto rounded-xl border border-border">
                          <table className="w-full text-sm">
                            <caption className="px-4 py-2 text-left font-medium text-foreground bg-muted/50 border-b border-border">
                              {locale === "uz" ? table.titleUz : table.titleRu}
                            </caption>
                            <thead>
                              <tr className="bg-muted/30">
                                {table.headers.map((h, hIdx) => (
                                  <th
                                    key={hIdx}
                                    className="px-4 py-2.5 text-left font-medium text-foreground border-b border-border"
                                  >
                                    {locale === "uz" ? h.uz : h.ru}
                                  </th>
                                ))}
                              </tr>
                            </thead>
                            <tbody>
                              {table.rows.map((row, rIdx) => {
                                const cells = locale === "uz" ? row.uz : row.ru
                                return (
                                  <tr
                                    key={rIdx}
                                    className={rIdx % 2 === 0 ? "bg-card" : "bg-muted/20"}
                                  >
                                    {cells.map((cell, cIdx) => (
                                      <td
                                        key={cIdx}
                                        className="px-4 py-2 text-muted-foreground border-b border-border last:border-b-0"
                                      >
                                        {cell}
                                      </td>
                                    ))}
                                  </tr>
                                )
                              })}
                            </tbody>
                          </table>
                        </div>
                      ))}
                    </div>
                  )
                })()}

                {/* FAQ Accordion */}
                {faqItems && faqItems.length > 0 && (
                  <div className="mt-8">
                    <h3 className="text-lg sm:text-xl font-semibold text-foreground mb-4">
                      {t("faq_heading")}
                    </h3>
                    <Accordion className="rounded-xl border border-border bg-card px-4">
                      {faqItems.map((item, index) => (
                        <AccordionItem key={index} value={`faq-${index}`}>
                          <AccordionTrigger className="text-left text-foreground">
                            {item.question}
                          </AccordionTrigger>
                          <AccordionContent>
                            <p className="text-muted-foreground">{item.answer}</p>
                          </AccordionContent>
                        </AccordionItem>
                      ))}
                    </Accordion>
                  </div>
                )}

                {/* Reviewed by — author byline */}
                {author && (
                  <Link
                    href={`/author/${author.slug}`}
                    className="mt-8 flex items-center gap-3 rounded-2xl border border-border bg-card p-4 transition-all hover:border-emerald-500/30 hover:bg-emerald-50/30 dark:hover:bg-emerald-950/20"
                  >
                    <div className="relative h-12 w-12 shrink-0 rounded-xl overflow-hidden ring-2 ring-emerald-500/20">
                      {/* eslint-disable-next-line @next/next/no-img-element */}
                      <img
                        src={author.imagePath}
                        alt={author.alternateName}
                        className="h-full w-full object-cover"
                      />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-1.5 text-xs text-muted-foreground mb-0.5">
                        <ShieldCheck className="h-3.5 w-3.5 text-emerald-600 dark:text-emerald-400" />
                        {locale === "uz" ? "Muallif va metodologiya" : "Автор и методология"}
                      </div>
                      <p className="font-semibold text-foreground text-sm">
                        {author.alternateName}
                      </p>
                      <p className="text-xs text-muted-foreground line-clamp-1">
                        {locale === "uz" ? author.jobTitleUz : author.jobTitleRu}
                      </p>
                    </div>
                    <ArrowRight className="h-4 w-4 text-muted-foreground shrink-0" />
                  </Link>
                )}
              </div>
            )}
          </div>

          {/* Sidebar */}
          <div className="lg:col-span-1 space-y-6">
            {/* Related Calculators */}
            {relatedCalculators.length > 0 && (
              <div className="rounded-2xl border border-border bg-card p-6">
                <h3 className="font-semibold text-foreground mb-4">
                  {t("related_title")}
                </h3>
                <div className="space-y-3">
                  {relatedCalculators.map((related) => {
                    const relatedTitle =
                      locale === "uz" ? related.titleUz : related.titleRu
                    const relatedLocalizedSlug = getSlugByLocale(related.slug, locale)
                    return (
                      <Link
                        key={related.slug}
                        href={`/calculator/${relatedLocalizedSlug}`}
                        className="group flex items-center gap-3 p-3 rounded-xl hover:bg-accent transition-colors"
                      >
                        <div
                          className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-lg ${category.color}`}
                        >
                          <DynamicIcon
                            name={related.icon}
                            className={`h-4 w-4 ${category.iconColor}`}
                          />
                        </div>
                        <div className="min-w-0 flex-1">
                          <p className="text-sm font-medium truncate group-hover:text-primary transition-colors">
                            {relatedTitle}
                          </p>
                        </div>
                        <ArrowRight className="h-4 w-4 shrink-0 text-muted-foreground group-hover:text-primary group-hover:translate-x-0.5 transition-all" />
                      </Link>
                    )
                  })}
                </div>
              </div>
            )}

            {/* Sources */}
            {article?.sources && article.sources.length > 0 && (
              <div className="rounded-2xl border border-border bg-card p-6">
                <h3 className="font-semibold text-foreground mb-4">
                  {t("sources_title")}
                </h3>
                <div className="space-y-2.5">
                  {article.sources.map((source, idx) => (
                    <a
                      key={idx}
                      href={source.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors group"
                    >
                      <ExternalLink className="h-3.5 w-3.5 shrink-0 group-hover:text-primary" />
                      <span>{source.name}</span>
                    </a>
                  ))}
                </div>
              </div>
            )}

            {/* SEO Info */}
            <div className="rounded-2xl border border-border bg-card p-6">
              <h3 className="font-semibold text-foreground mb-3">
                {t("calculator_about")}
              </h3>
              <p className="text-sm text-muted-foreground leading-relaxed">
                {description}
              </p>
              {calc.keywords.length > 0 && (
                <div className="flex flex-wrap gap-1.5 mt-4">
                  {calc.keywords.slice(0, 6).map((keyword) => (
                    <Badge
                      key={keyword}
                      variant="secondary"
                      className="text-xs"
                    >
                      {keyword}
                    </Badge>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
